from pathlib import Path
import pandas as pd,json,hashlib
from datetime import datetime,timezone
run=Path('E:/agent/mwangLab/output/native_codex_exercise_audit_expansion_20261002T201546Z'); src=run/'sources'; geo=pd.read_csv(src/'expansion_geo_ownership.csv')
# Manual paper-context adjudication: GSE232257 and GSE161882 are explicitly reused/reference datasets; GSE21340649 does not resolve to a usable GEO quick title.
reasons={'GSE232257':'rejected_reused_external_dataset','GSE161882':'rejected_reference/resource_example_not_article_owned','GSE21340649':'rejected_GEO_quick_record_has_no_matching_series_title'}
geo['selection_reason']='verified_article_owned'
for g,reason in reasons.items(): geo.loc[geo.accession==g,'ownership_verified']=False; geo.loc[geo.accession==g,'selection_reason']=reason
geo.to_csv(src/'expansion_geo_ownership.csv',index=False); ver=geo[geo.ownership_verified==True].copy(); rej=geo[geo.ownership_verified==False].copy(); ver.to_csv(src/'expansion_verified_accessions.csv',index=False); rej.to_csv(src/'expansion_rejected_accessions.csv',index=False)
pd.DataFrame([{'paper_id':x.paper_id,'pmcid':x.pmcid,'paper_title':x.title,'accession':x.accession,'geo_title':x.geo_title,'ownership_verified':True,'selection':'retained_paper_first_candidate','reason':'full-text deposition/availability context plus matching NCBI GEO quick metadata; Codex checked cited/reused accessions'} for _,x in ver.iterrows()]).to_csv(run/'expanded_summary.csv',index=False)
raw=pd.read_csv(src/'expansion_search_raw.csv'); ded=pd.read_csv(src/'expansion_search_deduplicated.csv'); am={'n_studies':16,'verdict_counts':{'justified':12,'false-positive-risk':2,'should-have-manual-review':2},'manual_review_count':2}
met={'prior_candidate_count':17,'expansion_query_count':8,'expansion_raw_search_rows':len(raw),'expansion_deduplicated_papers':len(ded),'full_text_with_accession':len(geo.pmcid.unique()),'verified_accession_rows':len(ver),'verified_new_papers':int(ver.pmcid.nunique()),'retained_additions':len(ver),'rejected_accession_rows':len(rej),'paper_first_rate':1.0,'supplemental_GEO_rate':0.0,'semantic_scholar_successes':8,'semantic_scholar_failures':0,'full_text_fetch_cap':15,'full_text_fetch_timeout_seconds':15}
(run/'audit_metrics.json').write_text(json.dumps(am,indent=2),encoding='utf-8'); (run/'metrics.json').write_text(json.dumps(met,indent=2),encoding='utf-8')
report=json.loads((run/'run_report.json').read_text(encoding='utf-8')); report['audit']=am; report['expansion']=met; report['comparison']['new_retained_additions']=len(ver); report['artifacts']['rejected']='sources/expansion_rejected_accessions.csv'; report['limitations']=['Full-text retrieval was bounded at 15 candidates and 15-second per-request timeout after slow endpoint responses; cap and partial coverage are explicit.','GSE232257 and GSE161882 were rejected as reused/reference accessions; GSE21340649 was rejected because its GEO quick record did not resolve a matching series title.','New additions are paper-first candidates; no DE analysis was run in this expansion pass.','Only accession-bearing full texts with a matching NCBI GEO quick record were retained; supplemental GEO rate is zero.']; (run/'run_report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf-8'); (run/'run_status.json').write_text(json.dumps({'run_id':run.name,'status':'completed_with_audit_and_expansion','study_total':16,'manual_review':2,'new_retained_additions':len(ver),'updated_at_utc':datetime.now(timezone.utc).isoformat()},indent=2),encoding='utf-8')
(run/'workflow.log').write_text('\n'.join([f'run_id={run.name}','decision_maker=current Codex conversation','external_llm_calls=0','route=Semantic Scholar + Europe PMC + OpenAlex + Crossref discovery; Europe PMC full text; NCBI GEO quick ownership','full_text_fetch_cap=15; timeout_seconds=15','supplemental_GEO_retained=0',f'new_verified_accession_rows={len(ver)}','rejected_reference_or_unresolved_accessions=3'])+'\n',encoding='utf-8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
items=[]
for p in sorted(run.rglob('*')):
 if p.is_file() and p.name!='artifact_index.json':items.append({'path':str(p.relative_to(run)),'bytes':p.stat().st_size,'sha256':sha(p)})
(run/'artifact_index.json').write_text(json.dumps(items,indent=2),encoding='utf-8'); print(json.dumps({'run':run.name,'audit':am,'expansion':met},indent=2))
