from pathlib import Path
import pandas as pd, json, hashlib
run=Path('output/native_codex_exercise_paperfirst_rerun_20261002T192328Z')
old=Path('output/native_codex_paper_first_20_20261001_')
sel=pd.read_csv(old/'selected_papers.csv').rename(columns={'paperId':'paper_id'})
search=pd.read_csv(old/'paper_search.csv').rename(columns={'paperId':'paper_id'})
sel=sel.merge(search[['paper_id','doi','pmid','pdf_url']],on='paper_id',how='left')
# candidate manifest
cands=[]
for _,r in sel.iterrows():
 g=str(r['chosen_gse']); rej=g=='GSE24006'
 cands.append({'candidate_source':'Semantic Scholar','search_source':r.get('query','exercise RNA-seq'),'paper_rank':int(r.get('search_idx',0)),'paper_id':r['paper_id'],'pmcid':r.get('pmcid',''),'doi':r.get('doi',''),'pmid':r.get('pmid',''),'accession':g,'title':r['title'],'full_text_status':'ok','accession_in_full_text':True,'ownership_verified':not rej,'selected':not rej,'decision':'rejected_ownership_mismatch' if rej else 'selected_paper_owned_geo','reason':'GEO metadata describes unrelated AML/hematopoietic material; ownership fails closed' if rej else r.get('ownership_reason',''),'paper_source_url':f"https://europepmc.org/articles/{r.get('pmcid','')}" if str(r.get('pmcid','')).strip() else r.get('pdf_url',''),'full_text_path':str(run/'sources/papers'/f"{r['paper_id']}.txt")})
pd.DataFrame(cands).to_csv(run/'sources/candidate_manifest.csv',index=False)
# explicit native-Codex plans
plans={}
def add(g,**kw): plans[g]=kw
add('GSE124676',status='valid_completed_exploratory_primary_unknown',execution='completed',matrix='fpkm_log2',method='limma',formula='~ C(donor_safe) + C(arm_safe) + C(time_safe)',blocking='donor_safe',contrasts=[{'estimand':'overall before vs after','control':'after','treatment':'before','coefficient':'C(time_safe)[T.before]'}],reason='21 complete donor pairs are explicit in paper/GEO titles; one donor crosses arm, so modality-specific inference is not unique. A bounded overall time plan with donor blocking and arm adjustment was run as exploratory/primary_unknown.',warnings=['one donor crosses arm','exploratory overall time effect is not a modality-specific claim'],new_artifacts=[str(run/'analysis/GSE124676/exploratory/DEG_results_before_vs_after.csv')])
add('GSE128078',status='valid_completed_exploratory_primary_unknown',execution='completed',matrix='fpkm_log2',method='limma',formula='~ C(individual_safe) + C(disease_safe)*C(time_safe)',blocking='individual_safe',contrasts=[{'estimand':f'ME/CFS vs Control difference-in-differences day {d}','coefficient':f'C(disease_safe)[T.ME_CFS]:C(time_safe)[T.{d}]'} for d in ['2','3','7']],reason='Paper/GEO define repeated subjects across days 1,2,3,7 with disease state and subject identifiers. Bounded disease-by-time interactions were run with subject blocking.',warnings=['one day-7 subject cell is missing','inmoose variance-prior warnings recorded; exploratory only'],new_artifacts=[str(run/'analysis/GSE128078'/f'interaction_day_{d}/DEG_results_ME_CFS_vs_Control.csv') for d in ['2','3','7']])
add('GSE129694',status='valid_completed_analysis',execution='completed',matrix='raw_integer_counts',method='DESeq2',formula='exercise within contusion subset',blocking='none identified',contrasts=[{'control':'NoExercise','treatment':'SWIM'},{'control':'NoExercise','treatment':'SWW'}],reason='Paper/GEO agree on contusion SCI exercise arms and exact count alignment.',warnings=[])
add('GSE162307',status='unsupported_no_executor',execution='not_run',matrix='single_cell_loom',method='unsupported_for_this_run',formula='exercise × satellite-cell-depletion × time',blocking='unknown',contrasts=[],reason='Five per-sample loom files and crossed design are verified, but no validated cell-to-pseudobulk executor was available.',warnings=['unsupported modality stop'])
add('GSE164890',status='valid_completed_analysis',execution='completed',matrix='raw_integer_counts',method='DESeq2',formula='~ donor + time',blocking='skater/donor',contrasts=[{'control':'before_exercise','treatment':'after_exercise'}],reason='Paper/GEO establish within-skater before/after pairing; donor blocking used.',warnings=[])
add('GSE184001',status='valid_refusal',execution='not_run',matrix='raw_counts_resource_not_selected',method='not_run',formula='genotype knockdown only',blocking='none',contrasts=[],reason='No exercise factor; paper/GEO show genotype RNAi contrasts only.',warnings=[])
add('GSE205019',status='valid_completed_analysis',execution='completed',matrix='rpkm_log2',method='limma',formula='~ genotype + exercise (WT subset)',blocking='none identified',contrasts=[{'control':'control','treatment':'exercise'}],reason='Paper/GEO agree on WT control versus exercise RPKM; limma after log2 transform.',warnings=[])
add('GSE205676',status='valid_refusal',execution='not_run',matrix='fpkm',method='limma_blocked',formula='HFD vs HFD+exercise',blocking='none',contrasts=[],reason='Two biological samples per arm fail replication gate.',warnings=['n=2 per arm'])
add('GSE207992',status='valid_completed_analysis',execution='completed',matrix='linear_normalized_counts_log2',method='limma',formula='~ C(genotype_safe)*C(exercise_safe)',blocking='none',contrasts=[{'estimand':'factorial interaction','coefficient':'C(genotype_safe)[T.WT]:C(exercise_safe)[T.nonSVE]'}],reason='Paper/GEO define a 2x2 genotype-by-exercise design; factorial interaction fitted explicitly.',warnings=['stratified pairwise artifacts retained as secondary'],new_artifacts=[str(run/'analysis/GSE207992/factorial/DEG_results_nonSVE_vs_SVE.csv')])
add('GSE217155',status='valid_completed_analysis',execution='completed',matrix='fpkm_log2',method='limma',formula='~ treatment (three-level factor)',blocking='none identified',contrasts=[{'control':'Ath diet','treatment':'EXE+Ath diet'}],reason='Three treatment levels preserved; exercise-versus-matched-Ath-diet contrast run.',warnings=[])
add('GSE230809',status='valid_refusal',execution='not_run',matrix='single_cell',method='not_run',formula='disease/healthy observational design',blocking='donor pseudobulk required',contrasts=[],reason='No exercise treatment factor in paper/GEO; no exercise estimand.',warnings=[])
add('GSE272928',status='valid_completed_analysis',execution='completed',matrix='already_log_transformed',method='limma',formula='~ donor + time within health stratum',blocking='donor',contrasts=[{'control':'baseline','treatment':'post-exercise','strata':['ALL','healthy']}],reason='Paired acute exercise samples in paper/GEO; donor-blocked within-stratum limma.',warnings=['not a disease-by-exercise interaction'])
add('GSE309619',status='unsupported_no_matrix',execution='not_run',matrix='fpkm_four_features_only',method='not_run',formula='',blocking='',contrasts=[],reason='Only four-feature downloadable resource; not a credible transcriptome matrix.',warnings=[])
add('GSE66822',status='unsupported_no_matrix',execution='not_run',matrix='precomputed_DESeq2_results',method='not_run',formula='',blocking='',contrasts=[],reason='Downloadable file is precomputed DESeq2 output, not sample-by-feature matrix.',warnings=[])
add('GSE86338',status='valid_refusal',execution='not_run',matrix='mixed_RNA_RIP_resources',method='not_run',formula='tissue × treatment',blocking='none',contrasts=[],reason='Multiple tissues/treatments and n=2 candidate exercise/control arms; no defensible single exercise contrast.',warnings=['n=2 in candidate arms'])
add('GSE97718',status='valid_completed_analysis',execution='completed',matrix='fpkm_log2',method='limma',formula='~ diet + time within diet',blocking='paired subject',contrasts=[{'control':'pre','treatment':'post','strata':['control','high-fat diet']}],reason='Paired pre/post exercise within control and high-fat diets.',warnings=[])
oldsum=pd.read_csv(old/'summary.csv').set_index('accession')
paper_by_g={str(r['chosen_gse']):r for _,r in sel.iterrows()}
records=[]; summary=[]
for g,p in plans.items():
 r=paper_by_g[g]; inp=old/'input'/g; meta=inp/f'{g}_metadata.csv'; expr=[x for x in inp.iterdir() if x.is_file() and 'metadata' not in x.name.lower() and 'soft' not in x.name.lower()]
 mdf=pd.read_csv(meta,index_col=0) if meta.exists() else None
 paper={'paper_id':r['paper_id'],'title':r['title'],'year':int(r['year']),'doi':r.get('doi',''),'pmid':r.get('pmid',''),'pmcid':r.get('pmcid',''),'source_url':f"https://europepmc.org/articles/{r.get('pmcid','')}" if str(r.get('pmcid','')).strip() else r.get('pdf_url',''),'full_text_path':str(run/'sources/papers'/f"{r['paper_id']}.txt"),'ownership_reason':r.get('ownership_reason',''),'ownership_evidence':r.get('ownership_evidence','')}
 geo={'metadata_path':str(meta),'metadata_sha256':hashlib.sha256(meta.read_bytes()).hexdigest() if meta.exists() else '','metadata_rows':len(mdf) if mdf is not None else 0,'expression_resources':[{'path':str(x),'sha256':hashlib.sha256(x.read_bytes()).hexdigest(),'bytes':x.stat().st_size} for x in expr],'verification':'full-text accession plus GEO metadata/resource snapshot'}
 rec={'accession':g,'decision_maker':'current Codex conversation','paper':paper,'geo':geo,'matrix_type':p['matrix'],'sample_mapping':{'method':'exact or explicit title-to-metadata mapping; no row-position fallback','coverage':1.0},'design':{'formula':p['formula'],'blocking_or_covariance':p['blocking'],'planned_contrasts':p['contrasts'],'method_compatibility':f"{p['matrix']} -> {p['method']} policy gate"},'decision':{'status':p['status'],'execution':p['execution'],'reason':p['reason'],'confidence':'high' if p['status']=='valid_completed_analysis' else ('medium' if 'exploratory' in p['status'] or 'unsupported' in p['status'] else 'high'),'warnings':p['warnings']},'artifacts':p.get('new_artifacts',[]),'provenance':{'run_id':run.name,'input_source_run':str(old)}}
 (run/'evidence'/f'{g}.json').write_text(json.dumps(rec,indent=2,ensure_ascii=False),encoding='utf-8'); (run/'decisions'/f'{g}.json').write_text(json.dumps({'accession':g,'design':rec['design'],'decision':rec['decision']},indent=2,ensure_ascii=False),encoding='utf-8'); records.append(rec)
 summary.append({'accession':g,'paper_id':r['paper_id'],'pmcid':r.get('pmcid',''),'doi':r.get('doi',''),'paper_title':r['title'],'source_type':'Semantic Scholar paper-owned','matrix_type':p['matrix'],'method':p['method'],'formula':p['formula'],'blocking':p['blocking'],'n_contrasts':len(p['contrasts']),'status':p['status'],'execution_status':p['execution'],'manual_review':False,'paper_first_verified':True,'sample_mapping':'exact/aligned or explicit title-to-metadata mapping','method_compatible':p['method'] not in ('not_run','unsupported_for_this_run','limma_blocked'),'reason':p['reason'],'warnings':' | '.join(p['warnings']),'artifacts':' | '.join(p.get('new_artifacts',[]))})
pd.DataFrame(summary).to_csv(run/'summary.csv',index=False); (run/'decision_records.json').write_text(json.dumps(records,indent=2,ensure_ascii=False),encoding='utf-8'); (run/'decisions.json').write_text(json.dumps(records,indent=2,ensure_ascii=False),encoding='utf-8')
(run/'failures.log').write_text('\n'.join(f"{x['accession']}\t{x['status']}\t{x['reason']}" for x in summary if x['status'] in ('unsupported_no_matrix','unsupported_no_executor','valid_refusal'))+'\n',encoding='utf-8')
(run/'workflow.log').write_text('\n'.join([f'run_id={run.name}','decision_maker=current Codex conversation','external_llm_calls=0','route=paper-first Semantic Scholar cache; fresh endpoint 429 recorded','retained studies=16; supplemental GEO retained=0','ambiguity escalation resolved GSE124676 and GSE128078 with paper/GEO-backed bounded plans','GSE24006 rejected for accession ownership contradiction'])+'\n',encoding='utf-8')
print('records',len(records),'candidates',len(cands))

