from pathlib import Path
import pandas as pd,json
run=Path('E:/agent/mwangLab/output/native_codex_exercise_audit_expansion_20261002T201546Z'); a=pd.read_csv(run/'audit/per_study_audit.csv'); e=pd.read_csv(run/'expanded_summary.csv'); met=json.loads((run/'metrics.json').read_text()); am=json.loads((run/'audit_metrics.json').read_text())
lines=[]; lines.append(f'# Native Codex exercise audit and paper-first expansion ({run.name})'); lines.append(''); lines.append('Decision-maker: current Codex conversation. External LLM calls: 0. The run audits the 16 retained studies from `native_codex_exercise_paperfirst_rerun_20261002T192328Z` and expands discovery beyond the prior 17 paper candidates.'); lines.append(''); lines.append('## Audit terminal report'); lines.append(''); lines.append(f"- Studies audited: {am['n_studies']}"); lines.append(f"- Verdicts: justified={am['verdict_counts']['justified']}; false-positive-risk={am['verdict_counts']['false-positive-risk']}; should-have-manual-review={am['verdict_counts']['should-have-manual-review']}"); lines.append(f"- Manual-review queue: {am['manual_review_count']} (GSE162307 executor/design review; GSE309619 data-recovery review)"); lines.append(''); lines.append('| Accession | Verdict | Prior status assessment | Key finding |'); lines.append('|---|---|---|---|');
for _,r in a.iterrows(): lines.append(f"| {r.accession} | {r.verdict} | {r.prior_status_assessment} | {str(r.reason).replace('|','/')} |")
lines.append(''); lines.append('GSE124676 is supported as a bounded exploratory overall time analysis: the paper specifies pre/post exercise, GEO has 21 complete pairs, and one donor crosses MET/Tai-chi labels, so modality-specific claims remain excluded. GSE128078 is retained as exploratory/primary_unknown because the paper uses a longitudinal disease-by-time question, but the GEO structure has 25 subjects, a missing day-7 cell, and a secondary interaction coding that should not be treated as confirmatory.'); lines.append(''); lines.append('## Expansion terminal report'); lines.append(''); lines.append(f"- Queries: {met['expansion_query_count']} across Semantic Scholar, Europe PMC, OpenAlex, and Crossref."); lines.append(f"- Search volume: {met['expansion_raw_search_rows']} raw rows, {met['expansion_deduplicated_papers']} deduplicated papers."); lines.append(f"- Full-text accession-bearing papers inspected under the bounded cap: {met['full_text_with_accession']}."); lines.append(f"- Verified new paper-owned accession rows retained: {met['retained_additions']} from {met['verified_new_papers']} papers."); lines.append(f"- `paper_first_rate`: {met['paper_first_rate']}; `supplemental_GEO_rate`: {met['supplemental_GEO_rate']}."); lines.append(f"- Full-text fetch cap/timeout: {met['full_text_fetch_cap']} candidates / {met['full_text_fetch_timeout_seconds']} seconds; endpoint errors and caps are preserved in `sources/expansion_api_log.csv`."); lines.append(''); lines.append('| New paper | Accession | GEO title |'); lines.append('|---|---|---|');
for _,r in e.iterrows(): lines.append(f"| {r.paper_title} ({r.pmcid}) | {r.accession} | {r.geo_title} |")
lines.append(''); lines.append('Three other accession mentions were rejected: GSE232257 and GSE161882 were explicitly reused/reference resources, and GSE21340649 did not resolve to a matching GEO quick record. No unlinked GEO hit was used to fill the target. No differential analysis was run for the new additions; they are retained paper-first candidates for a separate native decision pass.'); lines.append(''); lines.append('Artifacts: `audit/per_study_audit.csv`, `audit/GSE*.json`, `sources/expansion_search_raw.csv`, `sources/expansion_search_deduplicated.csv`, `sources/expansion_api_log.csv`, `sources/expansion_full_text_manifest.csv`, `sources/expansion_geo_ownership.csv`, `sources/expansion_rejected_accessions.csv`, `sources/expansion_verified_accessions.csv`, `expanded_summary.csv`, `run_report.json`, and `artifact_index.json`.')
(run/'final_summary.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
status=json.loads((run/'run_status.json').read_text()); status.update({'study_total':16,'study_completed':12,'study_manual_review':2,'study_unsupported':0,'study_refused':0,'audit_verdict_counts':am['verdict_counts'],'new_retained_additions':met['retained_additions'],'verified_new_papers':met['verified_new_papers']}); (run/'run_status.json').write_text(json.dumps(status,indent=2,ensure_ascii=False),encoding='utf-8'); print((run/'final_summary.md').read_text(encoding='utf-8'))
